### ISSUE TITLE
umdns: Potential cache corruption due to incorrect AVL tree traversal

### ISSUE THREAD

**Issue by mcroeder** [openwrt/mdnsd#2]
This issue was reported to the openwrt-devel mailing list in February. Since it did not seem to attract any attention, I'm trying it again here.

There is an issue in the umdns service that can lead to duplicate entries and lookup failures in the service data cache. The traversal of the AVL tree that maintains the cache records is done in an incorrect way in the two functions cache_record_find() and cache_host_is_known() of cache.c. The current code of these functions systematically misses the last AVL tree element (i.e., the last cache record).

The fix is trivial: Just use the correct AVL tree traversal approach of the function cache_dump_recursive() in cache.c in the two functions mentioned above as well. The attached patch [9990-metz-fix-cache-avl-traversal.patch.txt](https://github.com/openwrt/openwrt/files/8380376/9990-metz-fix-cache-avl-traversal.patch.txt) can be applied to the umdns package source directory.

**Comment by dhewg** [comment]
Was this resolved with c286c51a9bd931d023a55988c0e89574ee6d8ffa and can be closed?

**Comment by mcroeder** [comment]
Yes, c286c51a9bd931d023a55988c0e89574ee6d8ffa fixes it.

**Comment by PolynomialDivision** [comment]
However, now something else is broken. ^^ Several people report that umdns now needs a restart.

**Comment by rany2** [comment]
I don't think it's related to that commit. I was daily driving this patch when I made my comment here and it was working fine. I'm not sure when the issue started occurring though.
